name: generate snake animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" 
    - cron: "0 5 * * *"
    - cron: "0 13 * * *"
    - cron: "0 15 * * *"
    - cron: "0 17 * * *"
    - cron: "0 19 * * *"
    - cron: "0 21 * * *"
    - cron: "0 23 * * *"
 
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout repository 
        uses: actions/checkout@v4

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=black
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-pink.svg?color_snake=black&color_dots=#e6e9ed,#FFD2EF,#FFA2E8,#FF71DB,#FC4CD0 
            dist/github-snake-blue.svg?color_snake=black&color_dots=#e6e9ed,#C5D0FA,#99AFFE,#567DFD,#3D6AFF
            dist/github-snake-purple.svg?color_snake=black&color_dots=#e6e9ed,#E2C3FB,#C28DFF,#AC64FF,#8F33FF

      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake animation"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"